"""
Language context for EN/PT strings and small language-aware formatters.
"""

TRANSLATIONS = {
    "en": {
        "appName": "Flora Focus",
        "tagline": "Blossom into your best self",
        "createAccount": "Create an account",
        "enterEmailSignup": "Enter your email to sign up for this app",
        "enterEmailLogin": "Welcome back to your garden",
        "username": "Username",
        "chooseUsername": "Choose a username",
        "email": "Email",
        "emailPlaceholder": "email@domain.com",
        "password": "Password",
        "createPassword": "Create a password",
        "enterPassword": "Enter your password",
        "startGrowing": "Continue",
        "logIn": "Log In",
        "dontHaveAccount": "Don't have an account?",
        "alreadyHaveAccount": "Already have an account?",
        "signUp": "Sign up",
        "welcomeBack": "Welcome back!",
        "welcomeToApp": "Welcome to Flora Focus!",
        "garden": "Garden",
        "yourGarden": "'s Garden",
        "flowersBloomin": "flowers blooming",
        "gardenWaiting": "Your garden is waiting",
        "addTasksToGrow": "Add tasks to grow flowers!",
        "activeTasks": "Active Tasks",
        "addTask": "Add Task",
        "noActiveTasks": "No active tasks. Start growing your garden!",
        "completedTasks": "Completed Tasks",
        "taskCompleted": "Task completed!",
        "taskDeleted": "Task deleted",
        "logout": "Logout",
        "taskTitle": "Task Title",
        "taskTitlePlaceholder": "Water the plants",
        "description": "Description",
        "descriptionOptional": "Description (optional)",
        "descriptionPlaceholder": "Add details about this task...",
        "category": "Category",
        "priority": "Priority",
        "timeLimit": "Time Limit",
        "days": "Days",
        "hours": "Hours",
        "minutes": "Minutes",
        "cancel": "Cancel",
        "create": "Create",
        "update": "Update",
        "saving": "Saving...",
        "addNewTask": "Add New Task",
        "editTask": "Edit Task",
        "taskCreated": "Task created!",
        "taskUpdated": "Task updated!",
        "expired": "Expired",
        "general": "General",
        "work": "Work",
        "personal": "Personal",
        "health": "Health",
        "study": "Study",
        "low": "Low",
        "medium": "Medium",
        "high": "High",
        "stats": "Stats",
        "yourProgress": "Your Progress",
        "completionRate": "Completion Rate",
        "tasksCompleted": "tasks completed",
        "active": "Active Tasks",
        "completed": "Completed",
        "flowers": "Flowers",
        "expiredTasks": "Expired",
        "keepItUp": "Keep it up",
        "gardenFlourishing": "Your garden is flourishing! You're doing an amazing job.",
        "greatProgress": "You're making great progress! Keep completing tasks.",
        "everyTask": "Every task completed helps your garden grow. Start small!",
        "statsNoTasksTitle": "Ready when you are",
        "statsNoTasksMessage": "Create your first task when you want to start growing your garden.",
        "friends": "Friends",
        "gardenBuddies": "garden buddies",
        "addFriend": "Add Friend",
        "friendRequests": "Friend Requests",
        "yourFriends": "Your Friends",
        "noFriends": "No friends yet",
        "accept": "Accept",
        "viewGarden": "Garden",
        "friendEmail": "Friend's Email",
        "sendRequest": "Send Request",
        "friendRequestSent": "Friend request sent!",
        "friendRequestAccepted": "Friend request accepted!",
        "noFlowers": "No flowers yet",
        "family": "Family",
        "familyGroups": "Family Groups",
        "groups": "groups",
        "createGroup": "Create Group",
        "noFamilyGroups": "No family groups yet",
        "createGroupToManage": "Create a group to manage tasks together!",
        "assignTask": "Assign Task",
        "members": "Members",
        "groupName": "Group Name",
        "groupNamePlaceholder": "Our Family",
        "memberEmails": "Member Emails (comma-separated)",
        "maxMembers": "Maximum 7 members (8 including you)",
        "createFamilyGroup": "Create Family Group",
        "assignTo": "Assign To",
        "taskAssignedSuccess": "Task assigned successfully!",
        "admin": "admin",
        "member": "member",
        "profile": "Profile",
        "settings": "Settings",
        "saveChanges": "Save Changes",
        "deleteAccount": "Delete Account",
        "confirmPassword": "Confirm password",
        "avatarUrl": "Profile picture URL",
        "avatarPlaceholder": "https://example.com/avatar.png",
        "deleteAccountWarning": "This permanently removes your account and data.",
        "accountDeleted": "Account deleted",
        "profileUpdated": "Profile updated",
        "usernameUpdated": "Username updated",
        "confirmDelete": "Type your password to delete your account.",
    },
    "pt": {
        "appName": "Flora Focus",
        "tagline": "Floresce na tua melhor versao",
        "createAccount": "Criar conta",
        "enterEmailSignup": "Insere o teu email para criares conta",
        "enterEmailLogin": "Bem-vindo de volta ao teu jardim",
        "username": "Nome de utilizador",
        "chooseUsername": "Escolhe um nome de utilizador",
        "email": "Email",
        "emailPlaceholder": "email@dominio.com",
        "password": "Palavra-passe",
        "createPassword": "Criar palavra-passe",
        "enterPassword": "Insere a tua palavra-passe",
        "startGrowing": "Continuar",
        "logIn": "Entrar",
        "dontHaveAccount": "Nao tens conta?",
        "alreadyHaveAccount": "Ja tens conta?",
        "signUp": "Registar",
        "welcomeBack": "Bem-vindo de volta!",
        "welcomeToApp": "Bem-vindo ao Flora Focus!",
        "garden": "Jardim",
        "yourGarden": "Jardim de",
        "flowersBloomin": "flores a florescer",
        "gardenWaiting": "O teu jardim esta a espera",
        "addTasksToGrow": "Adiciona tarefas para fazer crescer flores!",
        "activeTasks": "Tarefas ativas",
        "addTask": "Adicionar tarefa",
        "noActiveTasks": "Nao tens tarefas ativas. Comeca a fazer crescer o teu jardim!",
        "completedTasks": "Tarefas concluidas",
        "taskCompleted": "Tarefa concluida!",
        "taskDeleted": "Tarefa eliminada",
        "logout": "Sair",
        "taskTitle": "Titulo da tarefa",
        "taskTitlePlaceholder": "Regar as plantas",
        "description": "Descricao",
        "descriptionOptional": "Descricao (opcional)",
        "descriptionPlaceholder": "Adiciona detalhes sobre esta tarefa...",
        "category": "Categoria",
        "priority": "Prioridade",
        "timeLimit": "Limite de tempo",
        "days": "Dias",
        "hours": "Horas",
        "minutes": "Minutos",
        "cancel": "Cancelar",
        "create": "Criar",
        "update": "Atualizar",
        "saving": "A guardar...",
        "addNewTask": "Adicionar nova tarefa",
        "editTask": "Editar tarefa",
        "taskCreated": "Tarefa criada!",
        "taskUpdated": "Tarefa atualizada!",
        "expired": "Expirada",
        "general": "Geral",
        "work": "Trabalho",
        "personal": "Pessoal",
        "health": "Saude",
        "study": "Estudo",
        "low": "Baixa",
        "medium": "Media",
        "high": "Alta",
        "stats": "Estatisticas",
        "yourProgress": "O teu progresso",
        "completionRate": "Taxa de conclusao",
        "tasksCompleted": "tarefas concluidas",
        "active": "Tarefas ativas",
        "completed": "Concluidas",
        "flowers": "Flores",
        "expiredTasks": "Expiradas",
        "keepItUp": "Continua assim",
        "gardenFlourishing": "O teu jardim esta a florescer! Estas a fazer um trabalho incrivel.",
        "greatProgress": "Estas a fazer um otimo progresso! Continua a completar tarefas.",
        "everyTask": "Cada tarefa concluida ajuda o teu jardim a crescer. Comeca aos poucos!",
        "statsNoTasksTitle": "Pronto quando tu estiveres",
        "statsNoTasksMessage": "Cria a tua primeira tarefa quando quiseres comecar a fazer crescer o teu jardim.",
        "friends": "Amigos",
        "gardenBuddies": "amigos de jardim",
        "addFriend": "Adicionar amigo",
        "friendRequests": "Pedidos de amizade",
        "yourFriends": "Os teus amigos",
        "noFriends": "Ainda nao tens amigos",
        "accept": "Aceitar",
        "viewGarden": "Jardim",
        "friendEmail": "Email do amigo",
        "sendRequest": "Enviar pedido",
        "friendRequestSent": "Pedido de amizade enviado!",
        "friendRequestAccepted": "Pedido de amizade aceite!",
        "noFlowers": "Ainda nao ha flores",
        "family": "Familia",
        "familyGroups": "Grupos familiares",
        "groups": "grupos",
        "createGroup": "Criar grupo",
        "noFamilyGroups": "Ainda nao tens grupos familiares",
        "createGroupToManage": "Cria um grupo para gerirem tarefas em conjunto!",
        "assignTask": "Atribuir tarefa",
        "members": "Membros",
        "groupName": "Nome do grupo",
        "groupNamePlaceholder": "A nossa familia",
        "memberEmails": "Emails dos membros (separados por virgula)",
        "maxMembers": "Maximo de 7 membros (8 contigo)",
        "createFamilyGroup": "Criar grupo familiar",
        "assignTo": "Atribuir a",
        "taskAssignedSuccess": "Tarefa atribuida com sucesso!",
        "admin": "admin",
        "member": "membro",
        "profile": "Perfil",
        "settings": "Definicoes",
        "saveChanges": "Guardar alteracoes",
        "deleteAccount": "Eliminar conta",
        "confirmPassword": "Confirmar palavra-passe",
        "avatarUrl": "URL da fotografia de perfil",
        "avatarPlaceholder": "https://example.com/avatar.png",
        "deleteAccountWarning": "Isto remove a tua conta e os teus dados de forma permanente.",
        "accountDeleted": "Conta eliminada",
        "profileUpdated": "Perfil atualizado",
        "usernameUpdated": "Nome de utilizador atualizado",
        "confirmDelete": "Escreve a tua palavra-passe para eliminares a conta.",
    },
}


class LanguageContext:
    def __init__(self):
        self.language = "en"

    def toggle_language(self):
        self.language = "pt" if self.language == "en" else "en"

    def t(self, key):
        return TRANSLATIONS[self.language].get(key, key)

    def garden_title(self, username):
        if self.language == "pt":
            return f"{self.t('yourGarden')} {username}"
        return f"{username}{self.t('yourGarden')}"

    def tasks_progress(self, completed, total):
        if self.language == "pt":
            return f"{completed} de {total} {self.t('tasksCompleted')}"
        return f"{completed} of {total} {self.t('tasksCompleted')}"
